### ISSUE TITLE
Cannot create PDFs

### ISSUE THREAD

**Issue by halloleo** [ickc/pancritic#14]
I have installed `pancritic `and `pypandoc `(and later `panflute `as well) into a virtual environment. `pandoc `itself is installed and on the path.

When I issue

    pancritic -t latex -o scr.pdf scr.md

I get the message

```
Cannot use pypandoc.
Use panflute instead.
Cannot use panflute.
Stop converting and output original format instead
```

and no output.

What's going wrong?

**Comment by ickc** [comment]
Sorry I completely missed this.

Can you try

```sh
which -a pandoc
which -a python
python -c 'import panflute'
python -c 'import pypandoc'
```

And paste the results here?

It seems like a PATH and/or PYTHONPATH issue.
