### ISSUE TITLE
relicense to BSD 3-Clause License

### ISSUE THREAD

**Issue by ickc** [ickc/pancritic#15]
@alerque, sorry for the spam and frankly I haven't maintained this much lately. Similar to ickc/pantable#50, I'm just trying to relicense this into a more permissive license for formality (not that it may have a real impact...)

Let me know if I have your permission, as you're the only other contributor here so far. Thanks.

**Comment by alerque** [comment]
Yes, you do. My contributions to this project may be re-licensed and distributed under the terms of the BSD 3-Clause license.
