### ISSUE TITLE
Cannot use markdown

### ISSUE THREAD

**Issue by ghost** [ickc/pancritic#3]
pancritic always reports a `Cannot use markdown` error.

Input `test.md`:
```
{~~Hello~>Goodbye~~} World
==========================

Hi. This is me. Hello me!

-   Apple
-   {~~Banana~>Boysenberries~~}
-   Cucumber
-   {++Dogs++}

Ok.{++ This is pretty good.++}

{--Goodbye.--}

{++Hello.++}
```

Execute:
```
2831)Documents % pancritic -s -m m test.md -o test.html
Cannot use markdown.
Use markdown2 instead.
Cannot use markdown2.
Stop converting and output original format instead.
```

The output is, indeed, an HTML with CSS and Javascript, so it's basically working.  The error message is confusing and I don't know what other problems it may be masking.

OSX High Sierra; pancritic installed via pip (v18.1, Python 3.7).

**Comment by ickc** [comment]
If you want to use pandoc, try installing either panflute or pypandoc and choose the engine using `--engine`. These 2 libraries uses pandoc as the backend.
